### ISSUE TITLE
Video Card

### ISSUE THREAD

**Issue by RedMaps** [Kaichou-Project/kaichou-graduation#18]
![image](https://user-images.githubusercontent.com/16868419/122266075-b253e600-ced9-11eb-8e86-dccd8341939a.png)

**Comment by Mecki-Messer** [comment]
working on it

**Comment by Mecki-Messer** [comment]
any tipps regarding a responsive web player would be much appreciated

**Comment by ArticulateMemory** [comment]
@Mecki-Messer per https://github.com/Kaichou-Project/kaichou-graduation/pull/21#pullrequestreview-685810344 , it looks like you had trouble with the suggested responsive solution. Could you try reproducing the issue in a jsfiddle and pointing the issue out? Something like https://jsfiddle.net/e6w3rtj1/

**Comment by Mecki-Messer** [comment]
i fiddled a bit around with fiddle and tried different things, i dont know why it works now, but it does, maybe you can have a look at it still because they dont really scale perfectly, you can find it in my latest commit in the video PR

all i did was moving the width and height settings from the stylesheet into the ReactPlayers jsx tag. now that is confusing as heck since that really shouldnt make any difference at all which is why i havent tried that until now
